Repository soutaro/steep, pull requests merged in 2023-10, with the labels that each got.

#922 Fix type alias validation
  lib/steep/signature/validator.rb
  test/validation_test.rb
Labels: bug

#923 Better completion with module alias and `use` directives
  lib/steep/server/interaction_worker.rb
  lib/steep/services/completion_provider.rb
  lib/steep/services/type_name_completion.rb
  sig/steep/services/type_name_completion.rbs
  test/type_name_completion_test.rb
Labels: bug

#941 Fewer `UnresolvedOverloading`
  lib/steep/type_construction.rb
  sig/steep/diagnostic/ruby.rbs
  smoke/block/test_expectations.yml
  smoke/enumerator/test_expectations.yml
  test/type_check_test.rb
Labels: area/core

#942 Let label be whole method type in SignatureHelp
  lib/steep/server/interaction_worker.rb
Labels: area/lsp

#943 Let goto definition work from `UnresolvedOverloading` error calls
  lib/steep/type_construction.rb
  test/goto_service_test.rb
Labels: area/core, area/lsp

#877 Support type narrowing by `Module#<`
  lib/steep/ast/types/logic.rb
  lib/steep/interface/builder.rb
  lib/steep/type_inference/logic_type_interpreter.rb
  sig/steep/ast/types.rbs
  sig/steep/ast/types/logic.rbs
  test/logic_type_interpreter_test.rb
  test/type_check_test.rb
Labels: area/core

#944 Fix space in file path crash
  lib/steep/path_helper.rb
  lib/steep/services/stats_calculator.rb
  sig/steep/services/stats_calculator.rbs
  smoke/regression/hello world.rb
  smoke/regression/test_expectations.yml
  test/path_helper_test.rb
Labels: bug, area/frontend

#945 Let `[]=` call have correct type
  lib/steep/type_construction.rb
  test/type_check_test.rb
Labels: bug, area/core

#946 Test if a parameter is `_`
  lib/steep/type_construction.rb
  test/type_check_test.rb
Labels: bug, area/core

#951 Assign types on method calls in mlhs node
  lib/steep/services/completion_provider.rb
  lib/steep/type_construction.rb
  test/completion_provider_test.rb
Labels: area/core

#953 Check if `rescue` body has `bot` type
  lib/steep/type_construction.rb
  test/type_check_test.rb
Labels: area/core
